### ISSUE TITLE
what version of javaruntime is needed?

### ISSUE THREAD

**Issue by 40OIL** [indx0/Vless-Url-Builder#1]
what version of javaruntime is needed to run on win7 x64? I have Version 8 Update 431 installed (both x86 and x64), and I got this error:

```
C:\-Downloads->java -jar ./Vless-Url-Builder.jar C:\-Downloads-\222222.json

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/indexzero/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

or do I need to specify the path somehow via Linux?

**Comment by indx0** [comment]
Java 21 is required. I recommend using Eclipse Temurin JRE, which you can download here https://adoptium.net/temurin/releases/?arch=x64&os=windows&package=jre
